config/routes.rb
PlanetDarts::Application.routes.draw do

  root "pages#index"
  devise_for :users
  # resources :users, :only => [:create, :new, :show, :destroy]
  resources :pages, only: [:index, :new, :create]
  resources :scores, only: [:create]
  resources :locations, only: [:create, :new]
end

app/models/location.rb
class Location < ActiveRecord::Base
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :scores

  def avg_score
    score_total = 0
    num_of_scores = scores.length

    scores.each do |score|
      score_total += score.points
    end

    if num_of_scores == 0
      "No guesses"
    else
      (score_total / num_of_scores)
    end
  end

  def high_score
    if scores.length != 0
      scores.order(:points).last.points
    else
      "None"
    end
  end

  def low_score
    if scores.length != 0
      scores.order(:points).first.points
    else
      "None"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  def new
    @location = Location.new
  end

  def create
    # *****needs to be added
    # var latLng = new google.maps.LatLng(12.121221, 78.121212);
    #   streetViewService.getPanoramaByLocation(latLng, STREETVIEW_MAX_DISTANCE, function (streetViewPanoramaData, status) {
    #   if (status === google.maps.StreetViewStatus.OK) {
    #   //ok
    #   } else {
    #     //no ok
    #   }
    # });
    @location = Location.create(latitude: params[:location][:latitude],
                                longitude: params[:location][:longitude])
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if Location.all.size != 0
      location = Location.all.sample
      gon.start_lat = location.latitude.to_f
      gon.start_long = location.longitude.to_f
    end
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def create
    points = calc_points(score_params[:coord1], score_params[:coord2])
    score = Score.new(points: points)
    @distance = calc_distance(score_params[:coord1], score_params[:coord2])
    if current_user
      current_user.scores << score
    else
      @tempUser = User.new
      @tempUser.scores << score
    end
    respond_to do |f|
      f.js
      f.html { redirect_to root_path}
    end
  end

private
  def score_params
    params.require(:score).permit(:coord1, :coord2)
  end

  def calc_distance(coord1, coord2)

    point1 = coord1.split(',').map {|coord| coord.to_f * (Math::PI/180)}
    point2 = coord2.split(',').map {|coord| coord.to_f * (Math::PI/180)}

    dlat = point2[0] - point1[0]
    dlon = point2[1] - point1[1]

    area = (Math.sin(dlat / 2))**2 + Math.cos(point1[0]) *
           (Math.sin(dlon / 2))**2 * Math.cos(point2[0])
    circumference = 2 * Math.atan2( Math.sqrt(area), Math.sqrt(1-area))
    circumference * 3963
  end

  def calc_points(coord1, coord2)
    distance = calc_distance(coord1, coord2)
    (24901 - distance) / (distance / 10)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def show
  end

  def create
    user = User.find_by_name(params[:name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "You are now logged in!"
    else
      flash.now.alert = "Username or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_url, notice: "Account #{user.name} created"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confimation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PlanetDarts</title>
  <%= include_gon %>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
  <script type="text/javascript"
    src="https://maps.googleapis.com/maps/api/js?key=<%=ENV['APIKEY']%>&amp;sensor=false">
  </script>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar navbar-default navbar-fixed-top">
    <%= link_to "Planet Darts", root_url, class: "navbar-brand pull-left" %>
    <% if user_signed_in? %>
      <%= link_to "Log out", destroy_user_session_path, :method => :delete, class: "navbar-text pull-right" %>
      <div class="navbar-text pull-right">
        Logged in as <%= current_user.email %>
      </div>
      <%= link_to "Add a new location", new_location_path, class: "navbar-text pull-left" %>
    <% else %>
      <%= link_to "Log In", new_user_session_path, class: "navbar-text pull-right" %>
      <%= link_to "New User?", new_user_registration_path, class: "navbar-text pull-right" %>
    <% end %>
  </div>


  <% flash[:alert] %>
  <% flash[:notice] %>
  <%= yield %>

  <div class="navbar navbar-default navbar-fixed-bottom">
    <% if !current_user.nil? %>
      <div class="navbar-text">
        Your average score per guess: <span id="avg_score"><%= current_user.avg_score %></span>
      </div>
      <div class="navbar-text">
        Your high score: <span id="high_score"><%= current_user.high_score %></span>
      </div>
      <div class="navbar-text">
        Your low score: <span id="low_score"><%= current_user.low_score %></span>
      </div>
    <% end %>
  </div>

</body>
</html>

app/views/locations/new.html.erb
<div id="location_buddy">
  <h2>Add New Location</h2>
  <div class="col-md-3">
    <%= form_for @location do |f| %>
      <%= f.label :latitude %>
      <%= f.text_field :latitude, class: 'form-control' %>
      <%= f.label :longitude %>
      <%= f.text_field :longitude, class: 'form-control' %>
      <br/>
      <%= f.submit class: 'btn btn-info' %>
    <% end %>
  </div>
</div>

app/views/pages/index.html.erb
<div id="map_buddy">
  <div id="guess">
    <%= form_for Score.new do |f| %>
      <%= f.hidden_field :coord1, :value => 0 %>
      <%= f.hidden_field :coord2, :value => 0 %>
      <%= f.submit "Make Guess", class: "btn btn-primary" %>
    <% end %>
  </div>
  <div id="map-canvas"></div>
  <div id="pano"></div>
  <div id="guessMap"></div>
  <div class="text-center" id="guessScore">
    <br />
    <div id="scoreValue">You Scored: </div>
    <br />
    <div id="distance">Distance from Target: </div>
    <br />
    <%= link_to "Throw another Dart!", root_url, class: 'btn btn-primary' %>
  </div>
</div>

app/views/scores/create.js.erb
$('#guessMap').css('zIndex',6);
$('#guessScore').css('zIndex',7);
$('#distance').append('<%= @distance.to_i %> mi');
<% if current_user %>
  $('#scoreValue').append('<%= current_user.scores.last.points %>');
  $('#avg_score').text('<%= current_user.avg_score %>');
  $('#high_score').text('<%= current_user.high_score %>');
  $('#low_score').text('<%= current_user.low_score %>');
<% else %>
  $('#scoreValue').append('<%= @tempUser.scores.last.points %>');
<% end %>

app/views/static_pages/index.html.erb
<h1>Map of Things</h1>

<div style='width: 800px;'>
  <div id="map-canvas" style='width: 800px; height: 400px;'></div>
</div>

app/views/users/_form.html.erb
<h2 id="headline">Add New User</h2>
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="field form-group">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </div>
  <%= f.submit "Sign Up!", class: "btn btn-success" %>
<% end %>
</div>

app/views/users/new.html.erb
<h2 class="headline">New User Signup</h2>

<div class="form_buddy">
  <%= render "form" %>
</div>